# Generated by Django 5.1.2 on 2024-11-02 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mashina yaratilgan vaqti'),
        ),
    ]
